import { GovernmentAlert } from '@/types';

export const ACTIVE_GOVERNMENT_ALERTS: GovernmentAlert[] = [
  {
    id: 'ADV-2024-10-MP04',
    severity: 'red',
    severityLabelEn: 'Red Alert (Take Action)',
    severityLabelHi: 'लाल स्तर चेतावनी (तत्काल सावधानी)',
    source: 'India Meteorological Department (IMD Doppler Radar, Bhopal Hub)',
    titleEn: 'Severe Thunderstorm, Cloud-to-Ground Lightning & Hail Hazard',
    titleHi: 'अगले 4 घंटों में अति-तीव्र मेघगर्जन, आकाशीय बिजली एवं ओलावृष्टि की चेतावनी!',
    englishSummary: 'Severe Thunderstorm with 65+ km/h gusty squall lines, active convective hail cells, and heavy downpour expected in rural Indore districts.',
    hindiSummary: 'दोपहर 2:30 से शाम 6:30 के बीच 65 किमी/घंटा तेज़ आंधी, बादलों की भारी गड़गड़ाहट एवं ओले गिरने का तीव्र जोखिम है। खेतों से तुरंत सुरक्षित स्थानों पर जाएं।',
    affectedTehsils: ['हातोद (Hatod)', 'देपालपुर (Depalpur)', 'सांवेर (Sanwer)', 'बेटमा (Betma)'],
    validFrom: '14:30 IST',
    validTo: '18:30 IST',
    expiresInText: 'Expires in 3h 45m (18:30 IST)',
    radarTracked: true,
    audioScriptHi: 'सावधान किसान भाइयों! मौसम विभाग द्वारा इंदौर जिले की हातोद, देपालपुर और सांवेर तहसीलों में अगले चार घंटों के लिए भारी मेघगर्जन और ओलावृष्टि का रेड अलर्ट जारी किया गया है। तुरंत पक्के मकान में शरण लें और कटी फसल को तिरपाल से सुरक्षित बांधें।',
    audioScriptEn: 'Attention farmers! India Meteorological Department has issued a Red Alert for Hatod, Depalpur, and Sanwer blocks. Severe thunderstorm, lightning, and hail expected over the next 4 hours. Move indoors immediately and shelter harvested crops.',
    farmerDirectives: [
      {
        step: 1,
        titleEn: 'Move Indoors Immediately',
        titleHi: 'तुरंत पक्के सुरक्षित स्थान पर जाएं',
        descriptionEn: 'Do not stand under isolated trees, metal sheds, or open tractors. Lightning strikes are most lethal in open agricultural fields.',
        descriptionHi: 'खेत में अकेले पेड़ के नीचे या खुले ट्रैक्टर पर बिल्कुल न खड़े रहें। आकाशीय बिजली चमकने पर तुरंत पक्के कमरे या सुरक्षित ढलान में शरण लें।',
        icon: 'shelves',
        urgency: 'immediate',
        audioSnippetHi: 'खेत में अकेले पेड़ के नीचे या ट्रैक्टर पर न रहें। तुरंत पक्के मकान में जाएं।',
      },
      {
        step: 2,
        titleEn: 'Cover Harvested Crop with Tarpaulin',
        titleHi: 'कटी हुई उपज व अनाज को तिरपाल से कसकर बांधें',
        descriptionEn: 'Cover threshing floors or open bags of soybean, wheat, or chickpea with thick plastic tarpaulins and weigh them down with stones.',
        descriptionHi: 'खलिहान या मंडी में रखी सोयाबीन, गेहूं या चने की बोरियों को मोटे प्लास्टिक तिरपाल से ढककर पत्थरों से दबाएं ताकि तेज हवा में उड़े नहीं।',
        icon: 'warehouse',
        urgency: 'immediate',
        audioSnippetHi: 'खलिहान में रखी सोयाबीन या फसल को प्लास्टिक तिरपाल से ढककर पत्थरों से बांधें।',
      },
      {
        step: 3,
        titleEn: 'Disconnect Electric Tubewells & Motors',
        titleHi: 'सिंचाई मोटर व बिजली स्टार्टर स्विच बंद करें',
        descriptionEn: 'Switch off submersible pumps and high-tension irrigation lines to prevent transformer burnouts and electrical shocks.',
        descriptionHi: 'खेत में चल रहे ट्यूबवेल, सबमर्सिबल पंप के स्टार्टर तुरंत बंद करें ताकि बिजली गिरने से मोटर न जले और शॉर्ट सर्किट से बचाव हो।',
        icon: 'power_off',
        urgency: 'high',
        audioSnippetHi: 'खेत की मोटर व ट्यूबवेल के स्टार्टर तुरंत बंद करें ताकि मोटर जलने से बचे।',
      },
      {
        step: 4,
        titleEn: 'Secure Livestock in Pucca Cattle Shed',
        titleHi: 'मवेशियों को टीन शेड या पक्के बाड़े में बांधें',
        descriptionEn: 'Move cattle, goats, and calves away from barbed-wire fencing and metal poles into covered, dry shelters.',
        descriptionHi: 'गायों, बैलों व बकरियों को खुले तारों की बाड़ और खंभों से दूर हटाकर पक्के पशु शेड में बांधें ताकि ओलों व करंट से चोट न पहुंचे।',
        icon: 'pets',
        urgency: 'high',
        audioSnippetHi: 'पशुओं को लोहे के तारों और पेड़ों से दूर पक्के बाड़े में सुरक्षित बांधें।',
      },
    ],
  },
  {
    id: 'ADV-2024-10-MP05',
    severity: 'orange',
    severityLabelEn: 'Orange Alert (Be Prepared)',
    severityLabelHi: 'नारंगी स्तर चेतावनी (सतर्क रहें)',
    source: 'State Disaster Management Authority (SDMA, Madhya Pradesh)',
    titleEn: 'Pesticide Washout & Wind Squall Advisory',
    titleHi: 'कीटनाशक धुलाई एवं तेज़ हवा चेतावनी (छिड़काव स्थगित रखें)',
    englishSummary: 'Surface winds exceeding 35 km/h with 70% rain probability will wash off chemical sprays across Malwa crops.',
    hindiSummary: 'दोपहर बाद 35 किमी प्रति घंटे की रफ्तार से चलने वाली हवाओं व बारिश से कीटनाशक का असर समाप्त हो जाएगा। छिड़काव स्थगित रखें।',
    affectedTehsils: ['महू (Mhow)', 'उज्जैन ग्रामीण (Ujjain Rural)'],
    validFrom: '12:00 IST',
    validTo: '21:00 IST',
    expiresInText: 'Expires at 21:00 IST',
    radarTracked: true,
    audioScriptHi: 'किसान भाइयों, आज दोपहर बाद हवा और बारिश से कीटनाशक धुल जाएगा। अपनी दवा और पैसे की बर्बादी रोकें।',
    audioScriptEn: 'Farmers are advised to postpone pesticide spraying today due to wind squalls and high washout risk.',
    farmerDirectives: [
      {
        step: 1,
        titleEn: 'Postpone Chemical & Fungicide Spraying',
        titleHi: 'कीटनाशक व फफूंदनाशक छिड़काव स्थगित करें',
        descriptionEn: 'Rain within 6 hours of application renders systemic chemicals ineffective.',
        descriptionHi: 'दवा छिड़कने के 6 घंटे के भीतर बारिश होने से दवा बह जाती है और कीटों पर कोई असर नहीं होता।',
        icon: 'cancel',
        urgency: 'high',
        audioSnippetHi: 'आज छिड़काव न करें, परसों सुबह 6 बजे से मौसम साफ़ रहेगा।',
      },
      {
        step: 2,
        titleEn: 'Clear Drainage Furrows in Standing Crops',
        titleHi: 'खेत की जल निकासी नालियां साफ़ रखें',
        descriptionEn: 'Prevent water stagnation in black soil furrows to protect roots from fungal rotting.',
        descriptionHi: 'काली मिट्टी में पानी भरने से जड़ सड़न का खतरा होता है। खेत के निचले किनारों से पानी निकलने का रास्ता खोलें।',
        icon: 'water',
        urgency: 'precautionary',
        audioSnippetHi: 'खेत की नालियों से पानी निकलने का रास्ता साफ़ कर दें।',
      },
    ],
  },
];

export function getAlertsForLocation(locInput?: any): GovernmentAlert[] {
  const locName = typeof locInput === 'string' ? locInput : (locInput?.name || 'Indore');
  const district = typeof locInput === 'string' ? locInput : (locInput?.district || locInput?.city || 'Local District');
  const state = typeof locInput === 'string' ? 'India' : (locInput?.state || 'India');
  const lower = (locName + ' ' + district + ' ' + state).toLowerCase();

  // 1. LUCKNOW & CENTRAL UTTAR PRADESH CORRIDOR
  if (lower.includes('lucknow') || lower.includes('vrindavan') || lower.includes('uttar pradesh') || lower.includes('up')) {
    return [
      {
        id: 'ADV-2024-10-UP-LKO',
        severity: 'red',
        severityLabelEn: 'Red Alert (Take Immediate Action)',
        severityLabelHi: 'लाल स्तर चेतावनी (तत्काल सावधानी)',
        source: 'India Meteorological Department (IMD Doppler Radar, Lucknow Hub - Amausi)',
        titleEn: `Severe Thunderstorm, Cloud-to-Ground Lightning & Hail Hazard across ${district}`,
        titleHi: `${district} एवं आसपास के क्षेत्रों में अति-तीव्र मेघगर्जन, आकाशीय बिजली एवं ओलावृष्टि की चेतावनी!`,
        englishSummary: `Severe Thunderstorm with 60+ km/h gusty squall lines, active convective cells, and localized hail expected across Mohanlalganj, Sarojini Nagar, and Malihabad belts.`,
        hindiSummary: `दोपहर 2:30 से शाम 6:30 के बीच 60 किमी/घंटा तेज़ आंधी, बादलों की भारी गड़गड़ाहट एवं ओले गिरने का तीव्र जोखिम है। खुले खेतों व बागों से तुरंत सुरक्षित स्थानों पर जाएं।`,
        affectedTehsils: ['मोहनलालगंज (Mohanlalganj)', 'सरोजिनी नगर (Sarojini Nagar)', 'मलिहाबाद (Malihabad)', 'बक्शी का तालाब (Bakshi Ka Talab)'],
        validFrom: '14:30 IST',
        validTo: '18:30 IST',
        expiresInText: 'Expires in 3h 45m (18:30 IST)',
        radarTracked: true,
        audioScriptHi: `सावधान किसान भाइयों! मौसम विभाग द्वारा लखनऊ व ${district} में भारी मेघगर्जन और ओलावृष्टि का रेड अलर्ट जारी किया गया है। मलिहाबाद, मोहनलालगंज व सरोजिनी नगर में तेज आंधी का खतरा है। तुरंत पक्के मकान में शरण लें और उपज को तिरपाल से सुरक्षित ढकें।`,
        audioScriptEn: `Attention residents and farmers! IMD Amausi Radar has issued a Red Alert for ${district}, Mohanlalganj, and Malihabad blocks. Severe squall lines, hail, and lightning imminent. Move to safe shelter immediately.`,
        farmerDirectives: [
          {
            step: 1,
            titleEn: 'Immediate Lightning Shelter',
            titleHi: 'तुरंत पक्के सुरक्षित स्थान पर जाएं',
            descriptionEn: 'Evacuate open fields and orchards immediately. Do not shelter under isolated mango trees or near metal power towers.',
            descriptionHi: 'खेत या आम के बाग में अकेले पेड़ के नीचे बिल्कुल न रुकें। आकाशीय बिजली से बचाव हेतु तुरंत पक्के मकान में जाएं।',
            icon: 'shelves',
            urgency: 'immediate',
            audioSnippetHi: 'खेत या बाग में अकेले पेड़ के नीचे न रुकें, तुरंत पक्के मकान में जाएं।',
          },
          {
            step: 2,
            titleEn: 'Smart Coping: Mango Orchards & Vegetable Plots',
            titleHi: 'स्मार्ट रणनीति: आम के बाग व सब्जी फसलों का बचाव',
            descriptionEn: 'Support young grafts in Malihabad mango belts with bamboo stakes. Secure anti-hail/anti-bird nets over vegetable nurseries.',
            descriptionHi: 'मलिहाबाद बेल्ट में नए आम के पौधों को बांस की खपच्चियों से सहारा दें। सब्जियों की नर्सरी पर नेट कसकर बांधें।',
            icon: 'agriculture',
            urgency: 'high',
            audioSnippetHi: 'आम की नई कलमी शाखाओं को सहारा दें और सब्जियों की क्यारियों को सुरक्षित करें।',
          },
          {
            step: 3,
            titleEn: 'Mandi Tarpaulin Shielding',
            titleHi: 'मंडी व खलिहान में तिरपाल से अनाज ढकें',
            descriptionEn: 'Cover open produce at Dubagga, Mohanlalganj, and local mandis with waterproof tarpaulins weighed down by sandbags.',
            descriptionHi: 'दुबग्गा व मोहनलालगंज मंडी अथवा खलिहान में रखी उपज को मोटे तिरपाल से ढककर पत्थरों या बोरियों से दबाएं।',
            icon: 'warehouse',
            urgency: 'immediate',
            audioSnippetHi: 'मंडी व खलिहान में रखी उपज को मोटे तिरपाल से ढकें।',
          },
          {
            step: 4,
            titleEn: 'Disconnect Electric Submersibles & Pumps',
            titleHi: 'सबमर्सिबल व सिंचाई पंप के स्टार्टर बंद करें',
            descriptionEn: 'Switch off agricultural tubewell connections to protect motors and transformers from high-voltage lightning strikes.',
            descriptionHi: 'खेत के ट्यूबवेल व बोरवेल स्टार्टर बंद कर दें ताकि बिजली गिरने से मोटर न जले।',
            icon: 'power_off',
            urgency: 'high',
            audioSnippetHi: 'खेत के ट्यूबवेल स्टार्टर तुरंत बंद करें।',
          },
        ],
      },
      {
        id: 'ADV-2024-10-UP-ORANGE',
        severity: 'orange',
        severityLabelEn: 'Orange Alert (Be Prepared)',
        severityLabelHi: 'नारंगी स्तर चेतावनी (सतर्क रहें)',
        source: 'Uttar Pradesh State Disaster Management Authority (UPSDMA, Lucknow)',
        titleEn: 'Chemical Spray Washout & Gangetic Alluvial Drainage Advisory',
        titleHi: 'कीटनाशक धुलाई एवं जल-निकासी चेतावनी (छिड़काव स्थगित रखें)',
        englishSummary: `Intense surface showers will wash off foliar sprays and induce pooling in Gangetic alluvial topsoil across ${district}.`,
        hindiSummary: `दोपहर बाद तेज बारिश से कीटनाशक धुल जाएगा और दोमट मिट्टी में जल-जमाव का खतरा है। कीटनाशक छिड़काव स्थगित रखें।`,
        affectedTehsils: ['लखनऊ सदर (Lucknow Sadar)', 'गोसाईंगंज (Gosainganj)', 'इटौंजा (Itaunja)'],
        validFrom: '12:00 IST',
        validTo: '21:00 IST',
        expiresInText: 'Expires at 21:00 IST',
        radarTracked: true,
        audioScriptHi: `किसान भाइयों, आज कीटनाशक व यूरिया का छिड़काव रोक दें। बारिश से दवा धुल जाएगी और पैसा बर्बाद होगा। खेत की नालियां खोल दें।`,
        audioScriptEn: `Farmers in ${district} are advised to postpone chemical spraying today and clear drainage furrows in standing crops.`,
        farmerDirectives: [
          {
            step: 1,
            titleEn: 'Postpone Chemical Spraying & Top-Dressing',
            titleHi: 'कीटनाशक व यूरिया छिड़काव 48 घंटे टालें',
            descriptionEn: 'High washout index will dilute foliar nutrition and pesticides. Resume application once fair weather stabilizes.',
            descriptionHi: 'बारिश होने से यूरिया और कीटनाशक बह जाएंगे। मौसम साफ होने तक छिड़काव रोकें।',
            icon: 'cancel',
            urgency: 'high',
            audioSnippetHi: 'आज छिड़काव रोकें, मौसम साफ होने पर करें।',
          },
          {
            step: 2,
            titleEn: 'Open Alluvial Field Drainage Trenches',
            titleHi: 'खेत की मुख्य जलनिकासी नालियां तुरंत खोलें',
            descriptionEn: 'Clear sediment and weeds from tail-end field trenches to avoid root rotting in alluvial loam.',
            descriptionHi: 'खेत के निचले हिस्से की जल निकासी नाली साफ करें ताकि पानी जमा होकर जड़ों को न सड़ाए।',
            icon: 'water',
            urgency: 'precautionary',
            audioSnippetHi: 'खेत की जल निकासी नालियां तुरंत साफ कर दें।',
          },
        ],
      },
    ];
  }

  // 2. DELHI NCR & NORTHERN PLAINS
  if (lower.includes('delhi') || lower.includes('noida') || lower.includes('gurugram') || lower.includes('ghaziabad')) {
    return [
      {
        id: 'ADV-2024-10-NCR-01',
        severity: 'red',
        severityLabelEn: 'Red Alert (Dust Storm & Downpour)',
        severityLabelHi: 'लाल स्तर चेतावनी (धूल भरी आंधी व बारिश)',
        source: 'India Meteorological Department (IMD Doppler Radar, New Delhi Palam)',
        titleEn: `Severe Convective Squall Line & Dust Hazard across ${district}`,
        titleHi: `${district} एवं एनसीआर क्षेत्र में 65 किमी/घंटा धूल भरी आंधी व ओलों की चेतावनी!`,
        englishSummary: `Severe squall lines (65-75 km/h) approaching the Yamuna corridor with low visibility and convective lightning.`,
        hindiSummary: `अगले 3 घंटों में 65 से 75 किमी/घंटा की रफ्तार से आंधी और तेज बौछारें पड़ने की संभावना है। पेड़ों और कमजोर शेड से दूर रहें।`,
        affectedTehsils: [`${district} North`, `${district} South`, 'Yamuna Basin', 'Najafgarh Corridor'],
        validFrom: '14:00 IST',
        validTo: '19:00 IST',
        expiresInText: 'Expires in 4h (19:00 IST)',
        radarTracked: true,
        audioScriptHi: `सावधान! दिल्ली एनसीआर व ${district} में 65 किमी प्रति घंटा की आंधी और बारिश की चेतावनी है। सुरक्षित भवनों में रहें।`,
        audioScriptEn: `Red Alert issued for ${district} and Delhi NCR. High velocity wind squalls and heavy downpours imminent. Stay indoors.`,
        farmerDirectives: [
          {
            step: 1,
            titleEn: 'Secure Polyhouses & Greenhouse Sheeting',
            titleHi: 'पॉलीहाउस व टनल शीट्स को कसकर बांधें',
            descriptionEn: 'Strong cross-winds can tear UV polyfilms. Close side vents and tighten tie-down ratchets.',
            descriptionHi: 'तेज हवाओं से पॉलीहाउस की प्लास्टिक उड़ सकती है। वेंट्स बंद करें और रस्सियां कसें।',
            icon: 'warehouse',
            urgency: 'immediate',
            audioSnippetHi: 'पॉलीहाउस के वेंट्स बंद करें और तिरपाल कसें।',
          },
          {
            step: 2,
            titleEn: 'Cease Highway Transport of Open Perishables',
            titleHi: 'खुले वाहनों में फल व सब्जी परिवहन रोकें',
            descriptionEn: 'High crosswinds along Yamuna Expressway and peripheral highways risk vehicle sway and produce scattering.',
            descriptionHi: 'हाईवे पर तेज हवाओं से खुले ट्रकों में रखी सब्जियां उड़ने का खतरा है, वाहन सुरक्षित स्थान पर रोकें।',
            icon: 'local_shipping',
            urgency: 'high',
            audioSnippetHi: 'सब्जियों से भरे खुले वाहनों को सुरक्षित स्थान पर खड़ा करें।',
          },
        ],
      },
    ];
  }

  // 3. DEFAULT REGIONAL ALERT ADAPTED TO ACTIVE LOCATION
  return [
    {
      id: `ADV-${Date.now()}-${district.slice(0, 3).toUpperCase()}`,
      severity: 'red',
      severityLabelEn: 'Red Alert (Take Action)',
      severityLabelHi: 'लाल स्तर चेतावनी (तत्काल सावधानी)',
      source: `India Meteorological Department (IMD Doppler Radar, ${state} Regional Station)`,
      titleEn: `Severe Thunderstorm, Cloud-to-Ground Lightning & Hail Hazard in ${district}`,
      titleHi: `${district} एवं आसपास के क्षेत्रों में अगले 4 घंटों में अति-तीव्र मेघगर्जन व आंधी की चेतावनी!`,
      englishSummary: `Severe Thunderstorm with 60+ km/h gusty squall lines, active convective cells, and heavy localized downpour expected in ${district} jurisdiction.`,
      hindiSummary: `दोपहर बाद 60 किमी/घंटा तेज़ आंधी, बादलों की भारी गड़गड़ाहट एवं वर्षा का तीव्र जोखिम है। खेतों से तुरंत सुरक्षित स्थानों पर जाएं।`,
      affectedTehsils: [`${district} Sadar`, `${district} Rural`, `${district} East`, `${district} West`],
      validFrom: '14:30 IST',
      validTo: '18:30 IST',
      expiresInText: 'Expires in 3h 45m (18:30 IST)',
      radarTracked: true,
      audioScriptHi: `सावधान किसान भाइयों! मौसम विभाग द्वारा ${district} जिले में अगले चार घंटों के लिए भारी मेघगर्जन और आंधी का रेड अलर्ट जारी किया गया है। तुरंत पक्के मकान में शरण लें और कटी फसल को तिरपाल से सुरक्षित बांधें।`,
      audioScriptEn: `Attention farmers! India Meteorological Department has issued a Red Alert for ${district} and surrounding blocks. Severe thunderstorm, lightning, and wind squalls expected. Move indoors immediately.`,
      farmerDirectives: [
        {
          step: 1,
          titleEn: 'Move Indoors Immediately',
          titleHi: 'तुरंत पक्के सुरक्षित स्थान पर जाएं',
          descriptionEn: 'Do not stand under isolated trees, metal sheds, or open tractors. Lightning strikes are most lethal in open agricultural fields.',
          descriptionHi: 'खेत में अकेले पेड़ के नीचे या खुले ट्रैक्टर पर बिल्कुल न खड़े रहें। आकाशीय बिजली चमकने पर तुरंत पक्के कमरे में शरण लें।',
          icon: 'shelves',
          urgency: 'immediate',
          audioSnippetHi: 'खेत में अकेले पेड़ के नीचे न रहें, तुरंत पक्के मकान में जाएं।',
        },
        {
          step: 2,
          titleEn: `Protect Standing Crops & Mandi Produce in ${district}`,
          titleHi: 'कटी हुई उपज व अनाज को तिरपाल से कसकर बांधें',
          descriptionEn: 'Cover threshing floors or open bags with thick plastic tarpaulins and weigh them down with stones.',
          descriptionHi: 'खलिहान या मंडी में रखी उपज को मोटे प्लास्टिक तिरपाल से ढककर पत्थरों से दबाएं ताकि तेज हवा में उड़े नहीं।',
          icon: 'warehouse',
          urgency: 'immediate',
          audioSnippetHi: 'खलिहान में रखी फसल को प्लास्टिक तिरपाल से ढकें।',
        },
        {
          step: 3,
          titleEn: 'Disconnect Electric Tubewells & Motors',
          titleHi: 'सिंचाई मोटर व बिजली स्टार्टर स्विच बंद करें',
          descriptionEn: 'Switch off submersible pumps and irrigation lines to prevent transformer burnouts and electrical shocks.',
          descriptionHi: 'खेत में चल रहे ट्यूबवेल, सबमर्सिबल पंप के स्टार्टर तुरंत बंद करें ताकि बिजली गिरने से मोटर न जले।',
          icon: 'power_off',
          urgency: 'high',
          audioSnippetHi: 'खेत की मोटर व ट्यूबवेल के स्टार्टर तुरंत बंद करें।',
        },
      ],
    },
    {
      id: `ADV-${Date.now() + 1}-${district.slice(0, 3).toUpperCase()}`,
      severity: 'orange',
      severityLabelEn: 'Orange Alert (Be Prepared)',
      severityLabelHi: 'नारंगी स्तर चेतावनी (सतर्क रहें)',
      source: `State Disaster Management Authority (${state})`,
      titleEn: `Pesticide Washout & Drainage Stagnation Warning for ${district}`,
      titleHi: `${district} में कीटनाशक धुलाई एवं जल-निकासी चेतावनी (छिड़काव स्थगित रखें)`,
      englishSummary: `Surface winds exceeding 35 km/h with high rain probability will wash off chemical sprays across ${district} fields.`,
      hindiSummary: `दोपहर बाद तेज हवाओं व बारिश से कीटनाशक का असर समाप्त हो जाएगा। छिड़काव स्थगित रखें।`,
      affectedTehsils: [`${district} Rural Hub`, `${district} Border Block`],
      validFrom: '12:00 IST',
      validTo: '21:00 IST',
      expiresInText: 'Expires at 21:00 IST',
      radarTracked: true,
      audioScriptHi: `किसान भाइयों, आज दोपहर बाद हवा और बारिश से कीटनाशक धुल जाएगा। अपनी दवा और पैसे की बर्बादी रोकें।`,
      audioScriptEn: `Farmers in ${district} are advised to postpone pesticide spraying today due to wind squalls and high washout risk.`,
      farmerDirectives: [
        {
          step: 1,
          titleEn: 'Postpone Chemical & Fungicide Spraying',
          titleHi: 'कीटनाशक व फफूंदनाशक छिड़काव स्थगित करें',
          descriptionEn: 'Rain within 6 hours of application renders systemic chemicals ineffective.',
          descriptionHi: 'दवा छिड़कने के 6 घंटे के भीतर बारिश होने से दवा बह जाती है और कीटों पर कोई असर नहीं होता।',
          icon: 'cancel',
          urgency: 'high',
          audioSnippetHi: 'आज छिड़काव न करें, मौसम साफ़ होने पर करें।',
        },
        {
          step: 2,
          titleEn: 'Clear Field Drainage Furrows',
          titleHi: 'खेत की जल निकासी नालियां साफ़ रखें',
          descriptionEn: 'Prevent water stagnation in field furrows to protect roots from fungal rotting.',
          descriptionHi: 'खेत में पानी भरने से जड़ सड़न का खतरा होता है। पानी निकलने का रास्ता खोलें।',
          icon: 'water',
          urgency: 'precautionary',
          audioSnippetHi: 'खेत की नालियों से पानी निकलने का रास्ता साफ़ कर दें।',
        },
      ],
    },
  ];
}
