import { GovernmentAlert } from '@/types';

export const ACTIVE_GOVERNMENT_ALERTS: GovernmentAlert[] = [
  {
    id: 'ADV-2024-10-MP04',
    severity: 'red',
    severityLabelEn: 'Red Alert (Take Action)',
    severityLabelHi: 'लाल स्तर चेतावनी (तत्काल सावधानी)',
    source: 'India Meteorological Department (IMD Doppler Radar, Bhopal Hub)',
    titleEn: 'Severe Thunderstorm, Cloud-to-Ground Lightning & Hail Hazard',
    titleHi: 'अगले 4 घंटों में अति-तीव्र मेघगर्जन, आकाशीय बिजली एवं ओलावृष्टि की चेतावनी!',
    englishSummary: 'Severe Thunderstorm with 65+ km/h gusty squall lines, active convective hail cells, and heavy downpour expected in rural Indore districts.',
    hindiSummary: 'दोपहर 2:30 से शाम 6:30 के बीच 65 किमी/घंटा तेज़ आंधी, बादलों की भारी गड़गड़ाहट एवं ओले गिरने का तीव्र जोखिम है। खेतों से तुरंत सुरक्षित स्थानों पर जाएं।',
    affectedTehsils: ['हातोद (Hatod)', 'देपालपुर (Depalpur)', 'सांवेर (Sanwer)', 'बेटमा (Betma)'],
    validFrom: '14:30 IST',
    validTo: '18:30 IST',
    expiresInText: 'Expires in 3h 45m (18:30 IST)',
    radarTracked: true,
    audioScriptHi: 'सावधान किसान भाइयों! मौसम विभाग द्वारा इंदौर जिले की हातोद, देपालपुर और सांवेर तहसीलों में अगले चार घंटों के लिए भारी मेघगर्जन और ओलावृष्टि का रेड अलर्ट जारी किया गया है। तुरंत पक्के मकान में शरण लें और कटी फसल को तिरपाल से सुरक्षित बांधें।',
    audioScriptEn: 'Attention farmers! India Meteorological Department has issued a Red Alert for Hatod, Depalpur, and Sanwer blocks. Severe thunderstorm, lightning, and hail expected over the next 4 hours. Move indoors immediately and shelter harvested crops.',
    farmerDirectives: [
      {
        step: 1,
        titleEn: 'Move Indoors Immediately',
        titleHi: 'तुरंत पक्के सुरक्षित स्थान पर जाएं',
        descriptionEn: 'Do not stand under isolated trees, metal sheds, or open tractors. Lightning strikes are most lethal in open agricultural fields.',
        descriptionHi: 'खेत में अकेले पेड़ के नीचे या खुले ट्रैक्टर पर बिल्कुल न खड़े रहें। आकाशीय बिजली चमकने पर तुरंत पक्के कमरे या सुरक्षित ढलान में शरण लें।',
        icon: 'shelves',
        urgency: 'immediate',
        audioSnippetHi: 'खेत में अकेले पेड़ के नीचे या ट्रैक्टर पर न रहें। तुरंत पक्के मकान में जाएं।',
      },
      {
        step: 2,
        titleEn: 'Cover Harvested Crop with Tarpaulin',
        titleHi: 'कटी हुई उपज व अनाज को तिरपाल से कसकर बांधें',
        descriptionEn: 'Cover threshing floors or open bags of soybean, wheat, or chickpea with thick plastic tarpaulins and weigh them down with stones.',
        descriptionHi: 'खलिहान या मंडी में रखी सोयाबीन, गेहूं या चने की बोरियों को मोटे प्लास्टिक तिरपाल से ढककर पत्थरों से दबाएं ताकि तेज हवा में उड़े नहीं।',
        icon: 'warehouse',
        urgency: 'immediate',
        audioSnippetHi: 'खलिहान में रखी सोयाबीन या फसल को प्लास्टिक तिरपाल से ढककर पत्थरों से बांधें।',
      },
      {
        step: 3,
        titleEn: 'Disconnect Electric Tubewells & Motors',
        titleHi: 'सिंचाई मोटर व बिजली स्टार्टर स्विच बंद करें',
        descriptionEn: 'Switch off submersible pumps and high-tension irrigation lines to prevent transformer burnouts and electrical shocks.',
        descriptionHi: 'खेत में चल रहे ट्यूबवेल, सबमर्सिबल पंप के स्टार्टर तुरंत बंद करें ताकि बिजली गिरने से मोटर न जले और शॉर्ट सर्किट से बचाव हो।',
        icon: 'power_off',
        urgency: 'high',
        audioSnippetHi: 'खेत की मोटर व ट्यूबवेल के स्टार्टर तुरंत बंद करें ताकि मोटर जलने से बचे।',
      },
      {
        step: 4,
        titleEn: 'Secure Livestock in Pucca Cattle Shed',
        titleHi: 'मवेशियों को टीन शेड या पक्के बाड़े में बांधें',
        descriptionEn: 'Move cattle, goats, and calves away from barbed-wire fencing and metal poles into covered, dry shelters.',
        descriptionHi: 'गायों, बैलों व बकरियों को खुले तारों की बाड़ और खंभों से दूर हटाकर पक्के पशु शेड में बांधें ताकि ओलों व करंट से चोट न पहुंचे।',
        icon: 'pets',
        urgency: 'high',
        audioSnippetHi: 'पशुओं को लोहे के तारों और पेड़ों से दूर पक्के बाड़े में सुरक्षित बांधें।',
      },
    ],
  },
  {
    id: 'ADV-2024-10-MP05',
    severity: 'orange',
    severityLabelEn: 'Orange Alert (Be Prepared)',
    severityLabelHi: 'नारंगी स्तर चेतावनी (सतर्क रहें)',
    source: 'State Disaster Management Authority (SDMA, Madhya Pradesh)',
    titleEn: 'Pesticide Washout & Wind Squall Advisory',
    titleHi: 'कीटनाशक धुलाई एवं तेज़ हवा चेतावनी (छिड़काव स्थगित रखें)',
    englishSummary: 'Surface winds exceeding 35 km/h with 70% rain probability will wash off chemical sprays across Malwa crops.',
    hindiSummary: 'दोपहर बाद 35 किमी प्रति घंटे की रफ्तार से चलने वाली हवाओं व बारिश से कीटनाशक का असर समाप्त हो जाएगा। छिड़काव स्थगित रखें।',
    affectedTehsils: ['महू (Mhow)', 'उज्जैन ग्रामीण (Ujjain Rural)'],
    validFrom: '12:00 IST',
    validTo: '21:00 IST',
    expiresInText: 'Expires at 21:00 IST',
    radarTracked: true,
    audioScriptHi: 'किसान भाइयों, आज दोपहर बाद हवा और बारिश से कीटनाशक धुल जाएगा। अपनी दवा और पैसे की बर्बादी रोकें।',
    audioScriptEn: 'Farmers are advised to postpone pesticide spraying today due to wind squalls and high washout risk.',
    farmerDirectives: [
      {
        step: 1,
        titleEn: 'Postpone Chemical & Fungicide Spraying',
        titleHi: 'कीटनाशक व फफूंदनाशक छिड़काव स्थगित करें',
        descriptionEn: 'Rain within 6 hours of application renders systemic chemicals ineffective.',
        descriptionHi: 'दवा छिड़कने के 6 घंटे के भीतर बारिश होने से दवा बह जाती है और कीटों पर कोई असर नहीं होता।',
        icon: 'cancel',
        urgency: 'high',
        audioSnippetHi: 'आज छिड़काव न करें, परसों सुबह 6 बजे से मौसम साफ़ रहेगा।',
      },
      {
        step: 2,
        titleEn: 'Clear Drainage Furrows in Standing Crops',
        titleHi: 'खेत की जल निकासी नालियां साफ़ रखें',
        descriptionEn: 'Prevent water stagnation in black soil furrows to protect roots from fungal rotting.',
        descriptionHi: 'काली मिट्टी में पानी भरने से जड़ सड़न का खतरा होता है। खेत के निचले किनारों से पानी निकलने का रास्ता खोलें।',
        icon: 'water',
        urgency: 'precautionary',
        audioSnippetHi: 'खेत की नालियों से पानी निकलने का रास्ता साफ़ कर दें।',
      },
    ],
  },
];

export function getAlertsForLocation(district: string = 'Indore'): GovernmentAlert[] {
  return ACTIVE_GOVERNMENT_ALERTS;
}
