/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#bfc9c1',
        'surface-container-low': '#ecf6f1',
        'on-tertiary-fixed': '#251a00',
        'surface-container': '#e6f0eb',
        'inverse-on-surface': '#e9f3ee',
        'on-tertiary-container': '#fcd579',
        'secondary-fixed': '#ffdbd1',
        'surface-container-highest': '#dbe5e0',
        'on-error-container': '#93000a',
        'surface-tint': '#2c694e',
        'on-surface-variant': '#404943',
        'on-secondary-fixed-variant': '#862201',
        'secondary-container': '#fe7952',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#3b0900',
        outline: '#707973',
        background: '#f2fcf6',
        tertiary: '#5a4400',
        'tertiary-fixed-dim': '#e7c268',
        'tertiary-container': '#775b06',
        'on-tertiary-fixed-variant': '#5a4400',
        'surface-dim': '#d2dcd7',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        surface: '#f2fcf6',
        'surface-container-high': '#e0eae5',
        'primary-fixed-dim': '#95d4b3',
        'inverse-surface': '#29322f',
        'on-surface': '#141d1a',
        'on-primary-fixed': '#002114',
        'on-secondary': '#ffffff',
        'inverse-primary': '#95d4b3',
        'surface-bright': '#f2fcf6',
        primary: '#0f5238',
        secondary: '#a73918',
        'surface-variant': '#dbe5e0',
        'secondary-fixed-dim': '#ffb5a0',
        'on-error': '#ffffff',
        'on-background': '#141d1a',
        'on-primary-fixed-variant': '#0e5138',
        'on-secondary-container': '#6c1900',
        'tertiary-fixed': '#ffdf96',
        'primary-fixed': '#b1f0ce',
        'error-container': '#ffdad6',
        'on-primary-container': '#a8e7c5',
        'on-primary': '#ffffff',
        'primary-container': '#2d6a4f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'target-touch-kisan': '3.5rem',
        'target-touch-explorer': '2.75rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'margin-mobile': '1rem',
        'margin-tablet': '2rem',
        'margin-desktop': '3rem',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Noto Sans"', 'sans-serif'],
        sans: ['"Noto Sans"', '"Plus Jakarta Sans"', 'sans-serif'],
        'display-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Noto Sans"', 'sans-serif'],
        'body-md': ['"Noto Sans"', 'sans-serif'],
        'body-sm': ['"Noto Sans"', 'sans-serif'],
        'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'data-metric': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
